/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CrudsAdmin;

import Admin.AdminDashboard;
import Admin.Projectpage;
import config.dbConnector;
import config.Session;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import myApp.LoginForm;


/**
 *
 * @author PC15
 */
public class crud_project extends javax.swing.JFrame {

    /**
     * Creates new form add_users
     */
    public crud_project() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        user_id = new javax.swing.JTextField();
        uname = new javax.swing.JTextField();
        status = new javax.swing.JComboBox<>();
        add = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pname = new javax.swing.JTextField();
        date = new com.toedter.calendar.JDateChooser();
        due = new com.toedter.calendar.JDateChooser();
        update = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        p_id = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        description = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        salary = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(51, 255, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        user_id.setEnabled(false);
        jPanel2.add(user_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 220, 25));

        uname.setEnabled(false);
        uname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unameActionPerformed(evt);
            }
        });
        jPanel2.add(uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 220, 25));

        status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "Active", "Not Active", "Completed" }));
        jPanel2.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 220, 30));

        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel2.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 70, 28));

        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        jPanel2.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, 67, 28));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Date:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 83, 26));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Due Date:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 83, 26));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Maker ID");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 83, 26));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Status:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 83, 26));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Maker Name:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 119, 26));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Project Name:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, 26));
        jPanel2.add(pname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 220, 25));
        jPanel2.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 220, 25));
        jPanel2.add(due, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 220, 25));

        update.setText("Update");
        update.setEnabled(false);
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel2.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, -1, 28));

        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel2.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 67, 28));

        p_id.setEnabled(false);
        jPanel2.add(p_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 220, 25));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("p_id");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 83, 26));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Salary:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 83, 26));
        jPanel2.add(description, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 220, 60));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Description:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 83, 26));

        salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salaryActionPerformed(evt);
            }
        });
        jPanel2.add(salary, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 220, 25));

        jPanel1.add(jPanel2);
        jPanel2.setBounds(290, 0, 360, 450);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ADD Project FORM");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 30, 220, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Untitled Project.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 680, 450);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
       if (pname.getText().isEmpty() || description.getText().isEmpty() || salary.getText().isEmpty() ||
            date.getDate() == null || due.getDate() == null || status.getSelectedItem().equals("SELECT")) {
            JOptionPane.showMessageDialog(null, "All Fields Are Required and Status must be selected!");
            return;
        }

        dbConnector dbc = new dbConnector();
        String insertSQL = "INSERT INTO tbl_project (u_id, p_name, p_salary, p_description, p_date, p_duedate, p_status) VALUES (?, ?, ?, ?, ?, ?, ?)";

        try (PreparedStatement pstmt = dbc.getConnection().prepareStatement(insertSQL)) {
            java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
            String formattedDate = sdf.format(date.getDate());
            String formattedDueDate = sdf.format(due.getDate());

            pstmt.setString(1, user_id.getText());
            pstmt.setString(2, pname.getText());
            pstmt.setString(3, salary.getText());
            pstmt.setString(4, description.getText());
            pstmt.setString(5, formattedDate);
            pstmt.setString(6, formattedDueDate);
            pstmt.setString(7, status.getSelectedItem().toString());

            int affectedRows = pstmt.executeUpdate();
            if (affectedRows > 0) {
                JOptionPane.showMessageDialog(null, "Project Added Successfully!");

            } else {
                JOptionPane.showMessageDialog(null, "Failed to add project.");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Database error on insert: " + ex.getMessage());
        }
    }//GEN-LAST:event_addActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Session sess = Session.getInstance();
        salary.setText(sess.getP_salary());
        description.setText(sess.getP_description());

    if (sess.getU_id() == 0) {
        JOptionPane.showMessageDialog(null, "No Account. Login First!");
        LoginForm lf = new LoginForm();
        lf.setVisible(true);
        this.dispose();
        return;
    }

    p_id.setText(String.valueOf(sess.getP_id()));
    user_id.setText(String.valueOf(sess.getU_id()));

    try {
        dbConnector dbc = new dbConnector();
        String sql = "SELECT u_fname, u_lname FROM tbl_users WHERE u_id = ?";
        PreparedStatement pstmt = dbc.getConnection().prepareStatement(sql);
        pstmt.setInt(1, sess.getU_id());
        ResultSet rs = pstmt.executeQuery();

        if (rs.next()) {
            String u_fname = rs.getString("u_fname");
            String u_lname = rs.getString("u_lname");

            // Null-safe handling
            if (u_fname == null) u_fname = "";
            if (u_lname == null) u_lname = "";

            String fullName = (u_fname + " " + u_lname).trim();

            if (fullName.isEmpty()) {
                uname.setText("Unknown User");
            } else {
                uname.setText(fullName);
            }
        } else {
            uname.setText("Unknown User");
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Failed to load user name: " + e.getMessage());
    }        

    salary.setText(String.valueOf(sess.getP_salary()));
    }//GEN-LAST:event_formWindowActivated

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        AdminDashboard ads = new AdminDashboard();
            ads.setVisible(true);
            Projectpage pp = new Projectpage();
            pp.setVisible(true);
            ads.mainDesktop.add(pp);
            this.dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
               if (p_id.getText().isEmpty() || pname.getText().isEmpty() || salary.getText().isEmpty() || description.getText().isEmpty() ||
    date.getDate() == null || due.getDate() == null || status.getSelectedItem().equals("SELECT")) {
    JOptionPane.showMessageDialog(null, "All Fields Are Required and Status must be selected!");
} else {
    dbConnector dbc = new dbConnector();
    String sql = "UPDATE tbl_project SET u_id = ?, p_name = ?, p_salary = ?, p_description = ?, p_date = ?, p_duedate = ?, p_status = ? WHERE p_id = ?";
    try (PreparedStatement pst = dbc.connect.prepareStatement(sql)) {
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
        String formattedDate = sdf.format(date.getDate());
        String formattedDueDate = sdf.format(due.getDate());

        pst.setString(1, user_id.getText());
        pst.setString(2, pname.getText());
        pst.setString(3, salary.getText());
        pst.setString(4, description.getText());
        pst.setString(5, formattedDate);
        pst.setString(6, formattedDueDate);
        pst.setString(7, status.getSelectedItem().toString());
        pst.setString(8, p_id.getText());

        int rowsUpdated = pst.executeUpdate();
        if (rowsUpdated > 0) {
            JOptionPane.showMessageDialog(null, "Project Updated Successfully!");

            AdminDashboard ads = new AdminDashboard();
            ads.setVisible(true);

            Projectpage pp = new Projectpage();
            pp.setVisible(true);
            ads.mainDesktop.add(pp);

            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "No project found with the provided ID.");
        }
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, "Failed to update project. Error: " + ex.getMessage());
    }
}

    }//GEN-LAST:event_updateActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        pname.setText("");
        description.setText("");
        salary.setText("");
        date.setDate(null);
        due.setDate(null);
        status.setSelectedIndex(0);
    }//GEN-LAST:event_clearActionPerformed

    private void salaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salaryActionPerformed

    private void unameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(crud_project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(crud_project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(crud_project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(crud_project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new crud_project().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton add;
    private javax.swing.JButton cancel;
    private javax.swing.JButton clear;
    public com.toedter.calendar.JDateChooser date;
    public javax.swing.JTextField description;
    public com.toedter.calendar.JDateChooser due;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JTextField p_id;
    public javax.swing.JTextField pname;
    public javax.swing.JTextField salary;
    public javax.swing.JComboBox<String> status;
    public javax.swing.JTextField uname;
    public javax.swing.JButton update;
    public javax.swing.JTextField user_id;
    // End of variables declaration//GEN-END:variables
}
