/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adds;

import Admin.AdminDashboard;
import Admin.Projectpage;
import Admin.Taskpage;
import config.dbConnector;
import Admin.Userpage;
import config.Session;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import myApp.LoginForm;


/**
 *
 * @author PC15
 */
public class add_tasks extends javax.swing.JFrame {

    /**
     * Creates new form add_users
     */
    public add_tasks() {
        initComponents(); 
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        user_id = new javax.swing.JTextField();
        status = new javax.swing.JComboBox<>();
        add = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        date = new com.toedter.calendar.JDateChooser();
        due = new com.toedter.calendar.JDateChooser();
        update = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        pname = new javax.swing.JComboBox<>();
        ufname = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        t_id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(51, 255, 153));

        user_id.setEnabled(false);

        status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "Active", "Not Active", "Completed" }));

        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Start Date:");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Due Date:");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("User_id");

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Status:");

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Assign Name:");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Project Name:");

        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        pname.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Project", "Item 2", "Item 3", "Item 4" }));
        pname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnameActionPerformed(evt);
            }
        });

        ufname.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select User", "Item 2", "Item 3", "Item 4" }));
        ufname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ufnameActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("task_id");

        t_id.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(update, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cancel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pname, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(status, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ufname, 0, 220, Short.MAX_VALUE)
                            .addComponent(user_id, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addComponent(t_id, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addComponent(due, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_id, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(user_id, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pname, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(ufname, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(due, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(290, 50, 370, 370);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ADD TASK FORM");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 30, 220, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Untitled Project.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 680, 450);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        String p_name = (String) pname.getSelectedItem();
    String u_fname = (String) ufname.getSelectedItem();
    String t_status = (String) status.getSelectedItem();
    java.util.Date t_date = date.getDate();
    java.util.Date t_duedate = due.getDate();

    if (p_name.equals("Select Project") || u_fname.equals("Select User") || t_status.equals("SELECT") || t_date == null || t_duedate == null) {
        JOptionPane.showMessageDialog(null, "Please fill in all fields.");
        return;
    }

    java.sql.Date sqlt_date = new java.sql.Date(t_date.getTime());
    java.sql.Date sqlt_duedate = new java.sql.Date(t_duedate.getTime());

    Session session = Session.getInstance();
    int creatorId = session.getU_id();  // The user who is logged in

    dbConnector db = new dbConnector();

    try {
        // Step 1: Get p_id from project name
        String getPidQuery = "SELECT p_id FROM tbl_project WHERE p_name = ?";
        int p_id = -1;

        try (PreparedStatement pst = db.connect.prepareStatement(getPidQuery)) {
            pst.setString(1, p_name);
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                p_id = rs.getInt("p_id");
            } else {
                JOptionPane.showMessageDialog(null, "Project not found.");
                return;
            }
        }

        // Step 2: Get user_id from user name
        String getUidQuery = "SELECT u_id FROM tbl_users WHERE u_fname = ?";
        int user_id = -1;

        try (PreparedStatement pst = db.connect.prepareStatement(getUidQuery)) {
            pst.setString(1, u_fname);
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                user_id = rs.getInt("u_id");
            } else {
                JOptionPane.showMessageDialog(null, "User not found.");
                return;
            }
        }

        String insertQuery = "INSERT INTO tbl_task (p_id, u_id, p_name, u_fname, t_date, t_duedate, t_status) VALUES (?, ?, ?, ?, ?, ?, ?)";

        try (PreparedStatement pst = db.connect.prepareStatement(insertQuery)) {
            pst.setInt(1, p_id);
            pst.setInt(2, user_id);
            pst.setString(3, p_name);
            pst.setString(4, u_fname);
            pst.setDate(5, sqlt_date);
            pst.setDate(6, sqlt_duedate);
            pst.setString(7, t_status);

            int rowsAffected = pst.executeUpdate();

            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(null, "Task added successfully!");
            } else {
                JOptionPane.showMessageDialog(null, "Error adding task.");
            }
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_addActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
         Session sess = Session.getInstance();
    if (sess.getU_id() == 0) {
        JOptionPane.showMessageDialog(null, "No Account. Login First!");
        LoginForm lf = new LoginForm();
        lf.setVisible(true);
        this.dispose();
        return;
    }

    
    populateComboBoxes();

    // Set ID fields
    t_id.setText(String.valueOf(sess.getT_id()));
    user_id.setText(String.valueOf(sess.getU_id()));

    // ====== Set selected project name (pname) ======
    String sessionProjectName = sess.getP_name();
    if (sessionProjectName != null && !sessionProjectName.trim().isEmpty()) {
        boolean projectMatchFound = false;
        for (int i = 0; i < pname.getItemCount(); i++) {
            String item = pname.getItemAt(i).toString().trim();
            if (item.equalsIgnoreCase(sessionProjectName.trim())) {
                pname.setSelectedItem(item);
                projectMatchFound = true;
                break;
            }
        }
        if (!projectMatchFound) {
            pname.addItem(sessionProjectName);
            pname.setSelectedItem(sessionProjectName);
        }
    } else {
        pname.setSelectedItem("Select Project");
    }

    String sessionUserFname = sess.getU_fname();
    if (sessionUserFname != null && !sessionUserFname.trim().isEmpty()) {
        boolean userMatchFound = false;
        for (int i = 0; i < ufname.getItemCount(); i++) {
            String item = ufname.getItemAt(i).toString().trim();
            if (item.equalsIgnoreCase(sessionUserFname.trim())) {
                ufname.setSelectedItem(item);
                userMatchFound = true;
                break;
            }
        }
        if (!userMatchFound) {
            ufname.addItem(sessionUserFname);
            ufname.setSelectedItem(sessionUserFname);
        }
    } else {
        ufname.setSelectedItem("Select User");
    }

    pname.repaint();
    ufname.repaint();
}
    private void populateComboBoxes() {
    dbConnector db = new dbConnector();

    try {
        // Populate project names
        String sqlProjects = "SELECT p_name FROM tbl_project"; 
        ResultSet rsProjects = db.getData(sqlProjects);
        DefaultComboBoxModel<String> projectModel = new DefaultComboBoxModel<>();
        projectModel.addElement("Select Project");

        while (rsProjects.next()) {
            String projectName = rsProjects.getString("p_name");
            projectModel.addElement(projectName);
            System.out.println("Project Name loaded: " + projectName);  // Debug log
        }
        pname.setModel(projectModel);

        // Populate user names
        String sqlUsers = "SELECT u_fname FROM tbl_users";  
        ResultSet rsUsers = db.getData(sqlUsers);
        DefaultComboBoxModel<String> userModel = new DefaultComboBoxModel<>();
        userModel.addElement("Select User");

        while (rsUsers.next()) {
            String userName = rsUsers.getString("u_fname");
            userModel.addElement(userName);
            System.out.println("User Name loaded: " + userName);  // Debug log
        }
        ufname.setModel(userModel);
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, "Error fetching data: " + ex.getMessage());
    }
    }//GEN-LAST:event_formWindowActivated

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        AdminDashboard ads = new AdminDashboard();
            ads.setVisible(true);
            Taskpage tp = new Taskpage();
            tp.setVisible(true);
            ads.mainDesktop.add(tp);
            this.dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
    if (t_id.getText().isEmpty() || pname.getSelectedItem().equals("Select Project") || 
        ufname.getSelectedItem().equals("Select User") || date.getDate() == null || 
        due.getDate() == null || status.getSelectedItem().equals("SELECT")) {
        
        JOptionPane.showMessageDialog(null, "All fields are required and status must be selected!");
        return;
    }

    dbConnector db = new dbConnector();
    
    try {
        // Format dates
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
        String formattedDate = sdf.format(date.getDate());
        String formattedDueDate = sdf.format(due.getDate());

        String selectedProject = (String) pname.getSelectedItem();
        String selectedUser = (String) ufname.getSelectedItem();
        
        int p_id = -1;
        int u_id = -1;

        // Get project ID from project name
        String getPidQuery = "SELECT p_id FROM tbl_project WHERE p_name = ?";
        try (PreparedStatement pst = db.connect.prepareStatement(getPidQuery)) {
            pst.setString(1, selectedProject);
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                p_id = rs.getInt("p_id");
            } else {
                JOptionPane.showMessageDialog(null, "Project not found.");
                return;
            }
        }

        // Get user ID from user first name
        String getUidQuery = "SELECT u_id FROM tbl_users WHERE u_fname = ?";
        try (PreparedStatement pst = db.connect.prepareStatement(getUidQuery)) {
            pst.setString(1, selectedUser);
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                u_id = rs.getInt("u_id");
            } else {
                JOptionPane.showMessageDialog(null, "User not found.");
                return;
            }
        }

        // Now that we have correct p_id and u_id, update the task
        String sql = "UPDATE tbl_task SET p_id = ?, u_id = ?, p_name = ?, u_fname = ?, " +
                     "t_date = ?, t_duedate = ?, t_status = ? WHERE t_id = ?";

        try (PreparedStatement pst = db.connect.prepareStatement(sql)) {
            pst.setInt(1, p_id);
            pst.setInt(2, u_id);
            pst.setString(3, selectedProject);
            pst.setString(4, selectedUser);
            pst.setString(5, formattedDate);
            pst.setString(6, formattedDueDate);
            pst.setString(7, status.getSelectedItem().toString());
            pst.setInt(8, Integer.parseInt(t_id.getText()));  // Convert t_id to int

            int rowsAffected = pst.executeUpdate();

            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(null, "Task updated successfully!");
                AdminDashboard ads = new AdminDashboard();
                ads.setVisible(true);
                Taskpage pp = new Taskpage();
                pp.setVisible(true);
                ads.mainDesktop.add(pp);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Failed to update task.");
            }
        }

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
    }
    }//GEN-LAST:event_updateActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clearActionPerformed

    private void pnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnameActionPerformed
       
    }//GEN-LAST:event_pnameActionPerformed

    private void ufnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ufnameActionPerformed
        
    }//GEN-LAST:event_ufnameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(add_tasks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(add_tasks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(add_tasks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(add_tasks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new add_tasks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton add;
    private javax.swing.JButton cancel;
    private javax.swing.JButton clear;
    public com.toedter.calendar.JDateChooser date;
    public com.toedter.calendar.JDateChooser due;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JComboBox<String> pname;
    public javax.swing.JComboBox<String> status;
    public javax.swing.JTextField t_id;
    public javax.swing.JComboBox<String> ufname;
    public javax.swing.JButton update;
    public javax.swing.JTextField user_id;
    // End of variables declaration//GEN-END:variables
}
