/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Printer;

import Admin.AdminDashboard;
import Admin.Taskpage;
import config.PanelPrinter;
import config.Session;
import config.dbConnector;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import myApp.LoginForm;


/**
 *
 * @author PC15
 */
public class printer extends javax.swing.JFrame {   
    public printer() {
        initComponents();  
        loadTaskData();
        loadAssignedUserData();
    }
    private void loadTaskData() {
        Session sess = Session.getInstance();
        t_id.setText(String.valueOf(sess.getT_id()));
        p_name.setText(sess.getP_name());
        p_salary.setText(sess.getP_salary());
        t_status.setText(sess.getT_status());
        approver.setText(sess.getU_lname());    // Maker
    }

    private void loadAssignedUserData() {
        Session sess = Session.getInstance();
        String assignedUser = sess.getU_fname(); // Get assigned user's first name

        try {
            dbConnector dbc = new dbConnector();
            String query = "SELECT u_gender, u_email, u_contact FROM tbl_users WHERE u_fname = ?";
            java.sql.PreparedStatement pst = dbc.connect.prepareStatement(query);
            pst.setString(1, assignedUser);
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                u_gender.setText(rs.getString("u_gender"));
                u_email.setText(rs.getString("u_email"));
                u_contact.setText(rs.getString("u_contact"));
            } else {
                JOptionPane.showMessageDialog(this, "Assigned user not found in database.");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());
        }
    }


    public  ImageIcon ResizeImage(String ImagePath, byte[] pic, JLabel label) {
    ImageIcon MyImage = null;
        if(ImagePath !=null){
            MyImage = new ImageIcon(ImagePath);
        }else{
            MyImage = new ImageIcon(pic);
        }
        
    int newHeight = getHeightFromWidth(ImagePath, label.getWidth());

    Image img = MyImage.getImage();
    Image newImg = img.getScaledInstance(label.getWidth(), newHeight, Image.SCALE_SMOOTH);
    ImageIcon image = new ImageIcon(newImg);
    return image;
}
    public static int getHeightFromWidth(String imagePath, int desiredWidth) {
        try {
            File imageFile = new File(imagePath);
            BufferedImage image = ImageIO.read(imageFile);
            int originalWidth = image.getWidth();
            int originalHeight = image.getHeight();
            int newHeight = (int) ((double) desiredWidth / originalWidth * originalHeight);            
            return newHeight;
        } catch (IOException ex) {
            System.out.println("No image found!");
        }        
        return -1;
    }
       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        page = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        assign_name = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        image = new javax.swing.JLabel();
        t_id = new javax.swing.JLabel();
        approver = new javax.swing.JLabel();
        p_name = new javax.swing.JLabel();
        u_email = new javax.swing.JLabel();
        u_contact = new javax.swing.JLabel();
        u_gender = new javax.swing.JLabel();
        t_status = new javax.swing.JLabel();
        p_salary = new javax.swing.JLabel();
        user_id = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        cancels = new javax.swing.JToggleButton();
        prints = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel9.setText("jLabel9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        page.setBackground(new java.awt.Color(51, 255, 153));
        page.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Email:");
        page.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 100, 26));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Contact:");
        page.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 100, 26));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Approve By:");
        page.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 100, 26));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Gender:");
        page.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 100, 26));

        assign_name.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        assign_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        assign_name.setText("Last Name:");
        page.add(assign_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 100, 30));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Project Name:");
        page.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 100, 26));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Task ID:");
        page.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 100, 26));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("First Name:");
        page.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 100, 26));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Status:");
        page.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 100, 26));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Salary:");
        page.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 100, 26));

        image.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        image.setText("No I mage");
        image.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        page.add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 100, 100));

        t_id.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        t_id.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t_id.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        page.add(t_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 100, 26));

        approver.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        approver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        approver.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        page.add(approver, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 100, 26));

        p_name.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        p_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p_name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        page.add(p_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 100, 26));

        u_email.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        u_email.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        u_email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        page.add(u_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 100, 26));

        u_contact.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        u_contact.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        u_contact.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        page.add(u_contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 100, 26));

        u_gender.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        u_gender.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        u_gender.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        page.add(u_gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 100, 26));

        t_status.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        t_status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t_status.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        page.add(t_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 100, 26));

        p_salary.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        p_salary.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p_salary.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        page.add(p_salary, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 100, 26));

        user_id.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        user_id.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user_id.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        page.add(user_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 100, 26));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("User ID:");
        page.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 100, 26));

        jTextField1.setBackground(new java.awt.Color(51, 255, 153));
        jTextField1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        page.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 100, 26));

        jTextField2.setBackground(new java.awt.Color(51, 255, 153));
        jTextField2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        page.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 100, 26));

        jLabel22.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Salary Reciept");
        page.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, 30));

        jPanel1.add(page);
        page.setBounds(270, 10, 390, 430);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("TASK MANAGEMENT");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 10, 240, 30);

        jLabel23.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel23.setText("SYSTEM");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(20, 40, 140, 30);

        cancels.setText("Cancel");
        cancels.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelsActionPerformed(evt);
            }
        });
        jPanel1.add(cancels);
        cancels.setBounds(180, 100, 80, 30);

        prints.setText("Print");
        prints.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printsActionPerformed(evt);
            }
        });
        jPanel1.add(prints);
        prints.setBounds(180, 60, 80, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Untitled Project.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 680, 450);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Session sess = Session.getInstance();

    if (sess.getU_id() == 0) {
        JOptionPane.showMessageDialog(null, "No Account. Login First!");
        LoginForm lf = new LoginForm();
        lf.setVisible(true);
        this.dispose();
    } else {
        // Display CURRENT LOGGED-IN USER as the "Approver/Maker"
        user_id.setText(sess.getU_fname());

        // Set task details from session
        t_id.setText(String.valueOf(sess.getT_id()));
        p_name.setText(sess.getP_name());
        t_status.setText(sess.getT_status());
        p_salary.setText(sess.getP_salary());

        try {
            // Connect to DB
            config.dbConnector dbc = new config.dbConnector();
            Connection con = dbc.getConnection();

            // Get the assigned user's information based on task ID
            String query = "SELECT u.* FROM tbl_users u JOIN tbl_task t ON u.u_id = t.u_id WHERE t.t_id = ?";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setInt(1, sess.getT_id());

            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                user_id.setText(String.valueOf(rs.getInt("u_id")));                                
                u_email.setText(rs.getString("u_email"));
                u_contact.setText(rs.getString("u_contact"));
                u_gender.setText(rs.getString("u_gender"));
                // Optional: Load image
                // String imgPath = rs.getString("image_path");
                // image.setIcon(ResizeImage(imgPath, null, image));
            } else {
                JOptionPane.showMessageDialog(null, "No assigned user found for this task.");
            }

            rs.close();
            pst.close();

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error loading assigned user data.");
        }
    }
    }//GEN-LAST:event_formWindowActivated

    private void printsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printsActionPerformed
         JPanel myPanel = new JPanel();
      PanelPrinter pPrint = new PanelPrinter(page);
      pPrint.printPanel();
    }//GEN-LAST:event_printsActionPerformed

    private void cancelsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelsActionPerformed
        AdminDashboard ads = new AdminDashboard();
            ads.setVisible(true);
            Taskpage tp = new Taskpage();
            tp.setVisible(true);
            ads.mainDesktop.add(tp);
            this.dispose();
    }//GEN-LAST:event_cancelsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(printer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(printer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(printer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(printer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new printer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel approver;
    private javax.swing.JLabel assign_name;
    private javax.swing.JToggleButton cancels;
    private javax.swing.JLabel image;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel p_name;
    private javax.swing.JLabel p_salary;
    public javax.swing.JPanel page;
    private javax.swing.JToggleButton prints;
    private javax.swing.JLabel t_id;
    private javax.swing.JLabel t_status;
    private javax.swing.JLabel u_contact;
    private javax.swing.JLabel u_email;
    private javax.swing.JLabel u_gender;
    private javax.swing.JLabel user_id;
    // End of variables declaration//GEN-END:variables
}