/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Printer;

import config.Session;
import java.awt.Color;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import config.dbConnector;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author SCC-COLLEGE
 */
public class PrintTaskz extends javax.swing.JInternalFrame {

    /**
     * Creates new form Userpage
     */
    public PrintTaskz() {
        initComponents();
        
        displayData();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
        
        searchBar.setOpaque(false);
        searchBar.setBackground(new Color(0,0,0,0));
    }
    
   public void displayData() {
    try {
        dbConnector dbc = new dbConnector();
        String query =
            "SELECT u.u_id, t.t_id, p.p_name, p.p_salary, " +
            "u.u_fname, u.u_lname, u.u_email, u.u_contact, u.u_gender, u.u_status, " +
            "au.u_fname AS assign_u_fname, au.u_lname AS assign_u_lname, au.u_email AS assign_u_email, " +
            "au.u_contact AS assign_u_contact, au.u_gender AS assign_u_gender " +
            "FROM tbl_users u " +
            "JOIN tbl_task t ON u.u_id = t.u_id " +
            "JOIN tbl_project p ON t.p_id = p.p_id " +
            "LEFT JOIN tbl_users au ON au.u_id = CAST(t.user_assign AS UNSIGNED) " +
            "WHERE t.accept = 'accepted' AND u.u_type != 'admin'";

        ResultSet rs = dbc.getData(query);
        userTable.setModel(DbUtils.resultSetToTableModel(rs));

        userTable.getColumnModel().getColumn(0).setHeaderValue("User ID");
        userTable.getColumnModel().getColumn(1).setHeaderValue("Task ID");
        userTable.getColumnModel().getColumn(2).setHeaderValue("Project Name");
        userTable.getColumnModel().getColumn(3).setHeaderValue("Salary");
        userTable.getColumnModel().getColumn(4).setHeaderValue("First Name");
        userTable.getColumnModel().getColumn(5).setHeaderValue("Last Name");
        userTable.getColumnModel().getColumn(6).setHeaderValue("Email");
        userTable.getColumnModel().getColumn(7).setHeaderValue("Contact");
        userTable.getColumnModel().getColumn(8).setHeaderValue("Gender");
        userTable.getColumnModel().getColumn(9).setHeaderValue("Status");

        userTable.getColumnModel().getColumn(10).setHeaderValue("Assigned First Name");
        userTable.getColumnModel().getColumn(11).setHeaderValue("Assigned Last Name");
        userTable.getColumnModel().getColumn(12).setHeaderValue("Assigned Email");
        userTable.getColumnModel().getColumn(13).setHeaderValue("Assigned Contact");
        userTable.getColumnModel().getColumn(14).setHeaderValue("Assigned Gender");

    } catch (SQLException ex) {
        System.out.println("Errors: " + ex.getMessage());
    }
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        searchButton = new javax.swing.JButton();
        printbutton = new javax.swing.JButton();
        searchBar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchButton.setText("SEARCH");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        jPanel1.add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, -1, -1));

        printbutton.setText("PRINT");
        printbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(printbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        searchBar.setMinimumSize(new java.awt.Dimension(8, 20));
        searchBar.setPreferredSize(new java.awt.Dimension(8, 20));
        searchBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBarActionPerformed(evt);
            }
        });
        jPanel1.add(searchBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 230, 23));

        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(userTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 520, 250));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setText("TASK PAGE");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Untitled Project.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 380));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBarActionPerformed

    private void printbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printbuttonActionPerformed
       int row = userTable.getSelectedRow();
    if (row == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select a user to print.");
        return;
    }

    int u_id = Integer.parseInt(userTable.getValueAt(row, 0).toString());
    String fname = userTable.getValueAt(row, 1).toString();
    String lname = userTable.getValueAt(row, 2).toString();
    String email = userTable.getValueAt(row, 3).toString();
    String contact = userTable.getValueAt(row, 4).toString();
    String status = userTable.getValueAt(row, 5).toString();

    Session sess = Session.getInstance();
    sess.setU_id(u_id);
    sess.setU_fname(fname);
    sess.setU_lname(lname);
    sess.setU_email(email);
    sess.setU_contact(contact);
    sess.setU_status(status);

    printer p = new printer();
    p.setVisible(true);

    JFrame parent = (JFrame) SwingUtilities.getWindowAncestor(this);
    parent.dispose();
    }//GEN-LAST:event_printbuttonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
    try {
        String keyword = searchBar.getText().trim();
        dbConnector dbc = new dbConnector();
        String query =
    "SELECT u.u_id, t.t_id, p.p_name, p.p_salary, " +
    "u.u_fname, u.u_lname, u.u_email, u.u_contact, " +
    "u.u_gender, u.u_status " +
    "FROM tbl_users u " +
    "JOIN tbl_task t ON u.u_id = t.u_id " +
    "JOIN tbl_project p ON t.p_id = p.p_id " +
    "WHERE u.u_fname LIKE '%" + keyword + "%' " +
    "OR u.u_lname LIKE '%" + keyword + "%' " +
    "OR u.u_email LIKE '%" + keyword + "%' " +
    "OR p.p_name LIKE '%" + keyword + "%' " +
    "OR t.t_id LIKE '%" + keyword + "%'";

        ResultSet rs = dbc.getData(query);
        if (!rs.isBeforeFirst()) {
            javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel();
            model.setColumnIdentifiers(new String[]{"Message"});
            model.addRow(new Object[]{"No results found for \"" + keyword + "\""});
            userTable.setModel(model);
        } else {
            userTable.setModel(DbUtils.resultSetToTableModel(rs));

            // Set headers again to keep them readable after search
            userTable.getColumnModel().getColumn(0).setHeaderValue("User ID");
            userTable.getColumnModel().getColumn(1).setHeaderValue("Task ID");
            userTable.getColumnModel().getColumn(2).setHeaderValue("Project Name");
            userTable.getColumnModel().getColumn(3).setHeaderValue("Salary");
            userTable.getColumnModel().getColumn(4).setHeaderValue("First Name");
            userTable.getColumnModel().getColumn(5).setHeaderValue("Last Name");
            userTable.getColumnModel().getColumn(6).setHeaderValue("Email");
            userTable.getColumnModel().getColumn(7).setHeaderValue("Contact");
            userTable.getColumnModel().getColumn(8).setHeaderValue("Gender");
            userTable.getColumnModel().getColumn(9).setHeaderValue("Status");
        }
    } catch (SQLException ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Database error: " + ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_searchButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton printbutton;
    private javax.swing.JTextField searchBar;
    private javax.swing.JButton searchButton;
    public javax.swing.JTable userTable;
    // End of variables declaration//GEN-END:variables
}
