package myApp;

import Admin.AdminDashboard;
import User.UserDashboard;
import config.Session;
import config.dbConnector;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author PC15
 */
public class LoginForm extends javax.swing.JFrame {

    private static final Logger logger = Logger.getLogger(LoginForm.class.getName());
    static String status;
    static String type;
     
    public LoginForm() {
        initComponents();
        
    }

    public static String hashPassword(String password) {        
        try {
            java.security.MessageDigest md = java.security.MessageDigest.getInstance("SHA-256");
            byte[] hashedBytes = md.digest(password.getBytes());
            StringBuilder sb = new StringBuilder();
            for (byte b : hashedBytes) {
                sb.append(String.format("%02x", b));
            }
            return sb.toString();
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    
    public static void logAction(int userId, String action) {
        try {
            dbConnector connector = new dbConnector();
            Connection conn = connector.getConnection();
            String query = "INSERT INTO tbl_logs (u_id, l_action) VALUES (?, ?)";
            PreparedStatement pstmt = conn.prepareStatement(query);
            pstmt.setInt(1, userId);
            pstmt.setString(2, action);
            pstmt.executeUpdate();
        } catch (SQLException e) {
            logger.log(Level.SEVERE, "Failed to insert log into tbl_logs", e);
        }
    }
   
    public static boolean loginAcc(String username, String password) {
        dbConnector connector = new dbConnector();
        try (Connection conn = connector.getConnection()) {
            String hashedPass = hashPassword(password);
            String query = "SELECT * FROM tbl_users WHERE u_username = ? AND u_password = ?";
            PreparedStatement stmt = conn.prepareStatement(query);
            stmt.setString(1, username);
            stmt.setString(2, hashedPass);
            ResultSet resultSet = stmt.executeQuery();

            if (resultSet.next()) {
                status = resultSet.getString("u_status");
                type = resultSet.getString("u_type");

                Session sess = Session.getInstance();
                sess.setU_id(resultSet.getInt("u_id"));
                sess.setU_fname(resultSet.getString("u_fname"));
                sess.setU_lname(resultSet.getString("u_lname"));
                sess.setU_email(resultSet.getString("u_email"));
                sess.setU_username(resultSet.getString("u_username"));
                sess.setU_contact(resultSet.getString("u_contact"));
                sess.setU_gender(resultSet.getString("u_gender"));
                sess.setU_type(resultSet.getString("u_type"));
                sess.setU_status(resultSet.getString("u_status"));

                logAction(sess.getU_id(), "Login");
                logger.info("Login successful for user: " + username);
                return true;
            } else {
                // Try to get the user ID for failed attempt logging
                String checkUserQuery = "SELECT u_id FROM tbl_users WHERE u_username = ?";
                PreparedStatement checkStmt = conn.prepareStatement(checkUserQuery);
                checkStmt.setString(1, username);
                ResultSet rs = checkStmt.executeQuery();
                if (rs.next()) {
                    int uid = rs.getInt("u_id");
                    logAction(uid, "Login failed");
                }
                logger.warning("Login failed for user: " + username);
                return false;
            }
        } catch (SQLException ex) {
            logger.log(Level.SEVERE, "SQL error during login", ex);
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        showpassword = new javax.swing.JCheckBox();
        user = new javax.swing.JTextField();
        pass = new javax.swing.JPasswordField();
        login = new javax.swing.JButton();
        forgot = new javax.swing.JLabel();
        loginShort = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 255, 153));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LOGIN FORM");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(110, 80, 140, 40);

        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("TASK MANAGEMENT SYSTEM");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(140, 10, 420, 28);

        showpassword.setBackground(new java.awt.Color(204, 204, 204));
        showpassword.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        showpassword.setText("show password");
        showpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpasswordActionPerformed(evt);
            }
        });
        jPanel1.add(showpassword);
        showpassword.setBounds(390, 240, 100, 20);

        user.setBackground(new java.awt.Color(204, 204, 204));
        user.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Username", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 11))); // NOI18N
        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });
        jPanel1.add(user);
        user.setBounds(250, 150, 240, 40);

        pass.setBackground(new java.awt.Color(204, 204, 204));
        pass.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        pass.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Password"));
        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });
        jPanel1.add(pass);
        pass.setBounds(250, 200, 240, 40);

        login.setText("LOGIN");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        jPanel1.add(login);
        login.setBounds(420, 270, 70, 23);

        forgot.setBackground(new java.awt.Color(51, 51, 51));
        forgot.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        forgot.setForeground(new java.awt.Color(255, 255, 255));
        forgot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        forgot.setText("Forgot Password ?");
        forgot.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        forgot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgotMouseClicked(evt);
            }
        });
        jPanel1.add(forgot);
        forgot.setBounds(250, 240, 140, 20);

        loginShort.setBackground(new java.awt.Color(51, 51, 51));
        loginShort.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        loginShort.setForeground(new java.awt.Color(255, 255, 255));
        loginShort.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginShort.setText("Click Here To Register>>");
        loginShort.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        loginShort.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginShortMouseClicked(evt);
            }
        });
        jPanel1.add(loginShort);
        loginShort.setBounds(250, 270, 160, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Untitled Project.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 680, 450);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
       String username = user.getText();
        String password = new String(pass.getPassword());

        if (loginAcc(username, password)) {
            if (!status.equals("Active")) {
                JOptionPane.showMessageDialog(null, "In-Active Account, Contact Admin!!");
                logger.warning("Inactive account tried to login: " + username);
            } else {
                if (type.equals("ADMIN")) {
                    logger.info("Admin logged in: " + username);
                    JOptionPane.showMessageDialog(null, "Welcome Back ADMIN!!!");
                    new AdminDashboard().setVisible(true);
                    this.dispose();
                } else if (type.equals("USER")) {
                    logger.info("User logged in: " + username);
                    JOptionPane.showMessageDialog(null, "Welcome Back User!!!");
                    new UserDashboard().setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "No Account Type Found");
                    logger.warning("Unknown type login: " + username);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Invalid Account");
        }   
    }//GEN-LAST:event_loginActionPerformed

    private void loginShortMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginShortMouseClicked
        RegForm rf = new RegForm();
        rf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_loginShortMouseClicked

    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passActionPerformed

    private void showpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpasswordActionPerformed
        if (showpassword.isSelected()) {
        pass.setEchoChar((char) 0);
    } else {
        pass.setEchoChar('\u2022');
    }
    }//GEN-LAST:event_showpasswordActionPerformed

    private void forgotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotMouseClicked
        forgot f = new forgot();
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_forgotMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel forgot;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton login;
    public javax.swing.JLabel loginShort;
    private javax.swing.JPasswordField pass;
    private javax.swing.JCheckBox showpassword;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
