/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import Logs.Logs;
import config.Session;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import myApp.LoginForm;

/**
 *
 * @author PC15
 */
public class AdminDashboard extends javax.swing.JFrame {

    /**
     * Creates new form AdminDashboard
     */
    public AdminDashboard() {
        initComponents();
            
    }
    
    home h = new home();
    
    Color navcolor = new Color(51,255,153);
    Color headcolor = new Color(153,204,255);
    Color bodycolor = new Color(204,255,102);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        mainDesktop = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        report = new javax.swing.JButton();
        userPage = new javax.swing.JButton();
        projectPage = new javax.swing.JButton();
        taskPage = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        fname = new javax.swing.JLabel();
        lname = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        contact = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        home = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 255, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ADMIN DASHBOARD");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 190, 30));

        javax.swing.GroupLayout mainDesktopLayout = new javax.swing.GroupLayout(mainDesktop);
        mainDesktop.setLayout(mainDesktopLayout);
        mainDesktopLayout.setHorizontalGroup(
            mainDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );
        mainDesktopLayout.setVerticalGroup(
            mainDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );

        jPanel1.add(mainDesktop, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 540, -1));

        jPanel2.setBackground(new java.awt.Color(51, 255, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        report.setBackground(new java.awt.Color(204, 255, 102));
        report.setText("Reports");
        report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportActionPerformed(evt);
            }
        });
        jPanel2.add(report, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 240, -1, 40));

        userPage.setBackground(new java.awt.Color(204, 255, 102));
        userPage.setText("User Page");
        userPage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userPageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                userPageMouseExited(evt);
            }
        });
        userPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userPageActionPerformed(evt);
            }
        });
        jPanel2.add(userPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 120, 40));

        projectPage.setBackground(new java.awt.Color(204, 255, 102));
        projectPage.setText("Project Page");
        projectPage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                projectPageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                projectPageMouseExited(evt);
            }
        });
        projectPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectPageActionPerformed(evt);
            }
        });
        jPanel2.add(projectPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 120, 40));

        taskPage.setBackground(new java.awt.Color(204, 255, 102));
        taskPage.setText("Task Page");
        taskPage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                taskPageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                taskPageMouseExited(evt);
            }
        });
        taskPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taskPageActionPerformed(evt);
            }
        });
        jPanel2.add(taskPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 120, 40));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-user-50.png"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 90));

        fname.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        fname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fname.setText("fname:");
        jPanel2.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        lname.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lname.setText("lname:");
        jPanel2.add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        email.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        email.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        email.setText("email:");
        jPanel2.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        contact.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        contact.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        contact.setText("contact:");
        jPanel2.add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        gender.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        gender.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gender.setText("gender:");
        jPanel2.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        username.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        username.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        username.setText("username:");
        jPanel2.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 80, -1));

        home.setBackground(new java.awt.Color(204, 255, 102));
        home.setText("Home");
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeMouseExited(evt);
            }
        });
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        jPanel2.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 70, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 450));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Untitled Project.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 741, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void userPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userPageActionPerformed
        Userpage ap = new Userpage();
        mainDesktop.add(ap).setVisible(true);
    }//GEN-LAST:event_userPageActionPerformed

    private void userPageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userPageMouseEntered
        
    }//GEN-LAST:event_userPageMouseEntered

    private void userPageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userPageMouseExited
        
    }//GEN-LAST:event_userPageMouseExited

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        home h = new home();
        h.setVisible(true);
        mainDesktop.add(h);
        
        Session sess = Session.getInstance();
      
      if(sess.getU_id()==0){
          JOptionPane.showMessageDialog(null,"No Account. Login First!");
          LoginForm lf = new LoginForm();
          lf.setVisible(true);
          this.dispose();
      }else{
          username.setText(""+sess.getU_username());
          fname.setText(""+sess.getU_fname());
          lname.setText(""+sess.getU_lname());
          email.setText(""+sess.getU_email());
          contact.setText(""+sess.getU_contact());
          gender.setText(""+sess.getU_gender());
      }
    }//GEN-LAST:event_formWindowActivated

    private void projectPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectPageActionPerformed
        Projectpage pp = new Projectpage();
        mainDesktop.add(pp).setVisible(true);
    }//GEN-LAST:event_projectPageActionPerformed

    private void taskPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taskPageActionPerformed
        Taskpage tp = new Taskpage();
        mainDesktop.add(tp).setVisible(true);
    }//GEN-LAST:event_taskPageActionPerformed

    private void homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseEntered
        
    }//GEN-LAST:event_homeMouseEntered

    private void homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseExited
        
    }//GEN-LAST:event_homeMouseExited

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        home h = new home();
        mainDesktop.add(h).setVisible(true);
    }//GEN-LAST:event_homeActionPerformed

    private void reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportActionPerformed
         Logs l = new Logs();
        mainDesktop.add(l).setVisible(true);        
    }//GEN-LAST:event_reportActionPerformed

    private void projectPageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_projectPageMouseEntered
        
    }//GEN-LAST:event_projectPageMouseEntered

    private void projectPageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_projectPageMouseExited
        
    }//GEN-LAST:event_projectPageMouseExited

    private void taskPageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_taskPageMouseEntered
        
    }//GEN-LAST:event_taskPageMouseEntered

    private void taskPageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_taskPageMouseExited
        
    }//GEN-LAST:event_taskPageMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel contact;
    public javax.swing.JLabel email;
    public javax.swing.JLabel fname;
    public javax.swing.JLabel gender;
    public javax.swing.JButton home;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JLabel lname;
    public javax.swing.JDesktopPane mainDesktop;
    public javax.swing.JButton projectPage;
    public javax.swing.JButton report;
    public javax.swing.JButton taskPage;
    public javax.swing.JButton userPage;
    public javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
