/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import CrudsAdmin.crud_project;
import config.Session;
import java.awt.Color;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import config.dbConnector;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author SCC-COLLEGE
 */
public class Projectpage extends javax.swing.JInternalFrame {

    /**
     * Creates new form 
     */
    public Projectpage() {
        initComponents();
        
        displayData();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
        
        searchBar.setOpaque(false);
        searchBar.setBackground(new Color(0,0,0,0));
    }
    
    public void displayData(){
        try{
            dbConnector dbc = new dbConnector();
            ResultSet rs = dbc.getData("SELECT p_id, p_name, p_salary, p_description, u_fname, p_date, p_duedate, p_status FROM tbl_project");
            projectTable.setModel(DbUtils.resultSetToTableModel(rs));
            projectTable.getColumnModel().getColumn(0).setHeaderValue("P ID");
            projectTable.getColumnModel().getColumn(1).setHeaderValue("Project Name");
            projectTable.getColumnModel().getColumn(2).setHeaderValue("Salary");
            projectTable.getColumnModel().getColumn(3).setHeaderValue("Description");
            projectTable.getColumnModel().getColumn(4).setHeaderValue("Maker Name");
            projectTable.getColumnModel().getColumn(5).setHeaderValue("Start Date");
            projectTable.getColumnModel().getColumn(6).setHeaderValue("Due Date");
            projectTable.getColumnModel().getColumn(7).setHeaderValue("Status");
            
        }catch(SQLException ex){
                    System.out.println("Errors:"+ex.getMessage());
      
        }
        
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        refresh = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        add = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        deletebutton = new javax.swing.JButton();
        searchBar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        projectTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        refresh.setText("REFRESH");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        jPanel1.add(refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, -1));

        searchButton.setText("SEARCH");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        jPanel1.add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, -1, -1));

        add.setText("ADD");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        edit.setText("EDIT");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        jPanel1.add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 70, -1));

        deletebutton.setText("DELETE");
        deletebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebuttonActionPerformed(evt);
            }
        });
        jPanel1.add(deletebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, -1, -1));

        searchBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        searchBar.setMinimumSize(new java.awt.Dimension(8, 20));
        searchBar.setPreferredSize(new java.awt.Dimension(8, 20));
        searchBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBarActionPerformed(evt);
            }
        });
        jPanel1.add(searchBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 220, 23));

        projectTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(projectTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 520, 250));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setText("PROJECT PAGE");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Untitled Project.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 380));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBarActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        crud_project ap = new crud_project();
        ap.setVisible(true);
        
        JFrame parent = (JFrame) SwingUtilities.getWindowAncestor(this);
                        parent.dispose();
    }//GEN-LAST:event_addActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        int rowIndex = projectTable.getSelectedRow();

    if (rowIndex < 0) {
        JOptionPane.showMessageDialog(null, "Please select a project to edit.");
        return;
    }

    try {
        TableModel model = projectTable.getModel();
        int projectIdToEdit = (int) model.getValueAt(rowIndex, 0);

        dbConnector dbc = new dbConnector();
        String query = "SELECT * FROM tbl_project WHERE p_id = '" + projectIdToEdit + "'";
        ResultSet rs = dbc.getData(query);

        if (rs != null && rs.next()) {
            // Save project data to session
            Session session = Session.getInstance();
            session.setP_id(rs.getInt("p_id"));
            session.setP_name(rs.getString("p_name"));
            session.setP_salary(rs.getString("p_salary"));
            session.setP_description(rs.getString("p_description"));
            session.setU_fname(rs.getString("u_fname"));

            // Launch form and populate fields
            crud_project ap = new crud_project();
            ap.p_id.setText(String.valueOf(rs.getInt("p_id")));
            ap.user_id.setText(String.valueOf(rs.getInt("u_id")));
            ap.pname.setText(rs.getString("p_name"));
            ap.salary.setText(rs.getString("p_salary"));
            ap.description.setText(rs.getString("p_description"));
            ap.uname.setText(rs.getString("u_fname"));
            ap.date.setDate(rs.getDate("p_date"));
            ap.due.setDate(rs.getDate("p_duedate"));
            ap.status.setSelectedItem(rs.getString("p_status"));

            // Enable update mode
            ap.add.setEnabled(false);
            ap.update.setEnabled(true);

            ap.setVisible(true);

            // Close current frame
            JFrame parent = (JFrame) SwingUtilities.getWindowAncestor(this);
            parent.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Project not found.");
        }

    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, "Database error: " + ex.getMessage());
        ex.printStackTrace();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Unexpected error: " + e.getMessage());
        e.printStackTrace();
    }
    }//GEN-LAST:event_editActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        String keyword = searchBar.getText().trim();

    try {
        dbConnector dbc = new dbConnector();
        String query = "SELECT u_id, p_id, u_fname, p_name FROM tbl_project " +
                       "WHERE u_fname LIKE '%" + keyword + "%' " +
                       "OR p_name LIKE '%" + keyword + "%' " +
                       "OR p_id LIKE '%" + keyword + "%'";
        ResultSet rs = dbc.getData(query);

        if (!rs.isBeforeFirst()) {
            javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel();
            model.setColumnIdentifiers(new String[]{"Message"});
            model.addRow(new Object[]{"No results found for \"" + keyword + "\""});
            projectTable.setModel(model);
        } else {
            // Show search results
            projectTable.setModel(DbUtils.resultSetToTableModel(rs));
        }

    } catch (SQLException ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Database error: " + ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void deletebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebuttonActionPerformed
        int rowIndex = projectTable.getSelectedRow();

        if (rowIndex < 0) {
            JOptionPane.showMessageDialog(null, "Please select a user to delete.");
            return;
        }

        TableModel model = projectTable.getModel();
        String userId = model.getValueAt(rowIndex, 0).toString();  // Assuming u_id is in column 0

        int confirm = JOptionPane.showConfirmDialog(null,
                "Are you sure you want to delete this project?",
                "Confirm Deletion",
                JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            dbConnector dbc = new dbConnector();
            String query = "DELETE FROM tbl_project WHERE p_id = '" + userId + "'";
            dbc.deleteData(query);

            JOptionPane.showMessageDialog(null, "Project deleted successfully!");

            // Refresh the table data after deletion
            displayData();
        }
    }//GEN-LAST:event_deletebuttonActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        displayData();
    }//GEN-LAST:event_refreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton deletebutton;
    private javax.swing.JButton edit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable projectTable;
    private javax.swing.JButton refresh;
    private javax.swing.JTextField searchBar;
    private javax.swing.JButton searchButton;
    // End of variables declaration//GEN-END:variables
}
